#ifndef PHP_EXT_TAOS_H
# define PHP_EXT_TAOS_H

#include "ext_tdengine.h"

// TDengine functions
PHP_FUNCTION(setOptions);
PHP_FUNCTION(getClientInfo);
static const zend_function_entry ext_functions[] = {
	ZEND_NS_FE("TDengine", setOptions, arginfo_TDengine_setOptions)
	ZEND_NS_FE("TDengine", getClientInfo, arginfo_TDengine_getClientInfo)
	ZEND_FE_END
};

static void register_constants(int module_number)
{
    REGISTER_NS_LONG_CONSTANT("TDengine", "TSDB_OPTION_LOCALE", TSDB_OPTION_LOCALE, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("TDengine", "TSDB_OPTION_CHARSET", TSDB_OPTION_CHARSET, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("TDengine", "TSDB_OPTION_TIMEZONE", TSDB_OPTION_TIMEZONE, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("TDengine", "TSDB_OPTION_CONFIGDIR", TSDB_OPTION_CONFIGDIR, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("TDengine", "TSDB_OPTION_SHELL_ACTIVITY_TIMER", TSDB_OPTION_SHELL_ACTIVITY_TIMER, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("TDengine", "TSDB_MAX_OPTIONS", TSDB_MAX_OPTIONS, CONST_CS | CONST_PERSISTENT);
}

#endif	/* PHP_EXT_TAOS_H */
